export { default as assessment_meta } from './assessment_meta.xml'
export { default as imsmanifest } from './imsmanifest.xml'
export { default as multiple_answers_question} from './multiple_answers_question.xml'
export { default as multiple_choice_question } from './multiple_choice_question.xml'
export { default as multiple_dropdowns_question } from './multiple_dropdowns_question.xml'
export { default as quiz } from './quiz.xml'
export { default as respcondition } from './respcondition.xml'
export { default as response_label } from './response_label.xml'
export { default as response_lid } from './response_lid.xml'
export { default as short_answer_question } from './short_answer_question.xml'
export { default as varequal } from './varequal.xml'
